'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { z } from 'zod';
import { requireTenant,requireUser,requireAdmin } from '@/lib/auth';
import { createSupabase } from '@/lib/supabase/server';
import { barberSchema,serviceSchema,shopSchema,onboardingSchema,errorMessage } from '@/lib/validation';
import type { ActionResult } from '@/types/domain';
const uuid=z.string().uuid();
const values=(f:FormData)=>Object.fromEntries(f.entries());
export async function logout(){const db=await createSupabase();await db.auth.signOut();redirect('/login');}
export async function onboard(form:FormData):Promise<ActionResult>{const{db}=await requireUser();try{const data=onboardingSchema.parse({...values(form),price_cents:Math.round(Number(form.get('price'))*100)});const{error}=await db.rpc('create_barbershop',{p_data:data});if(error)throw error;return{redirect:'/dashboard',success:'Sua barbearia está pronta!'};}catch(error){return{error:errorMessage(error)};}}
export async function saveService(form:FormData):Promise<ActionResult>{const{db,shop}=await requireTenant();try{const data=serviceSchema.parse({...values(form),price_cents:Math.round(Number(form.get('price'))*100),active:form.get('active')==='on'});const id=form.get('id');const barberIds=z.array(uuid).parse(form.getAll('barber_ids'));const{error}=await db.rpc('save_service',{p_shop:shop.id,p_id:id?uuid.parse(id):null,p_data:data,p_barbers:barberIds});if(error)throw error;revalidatePath('/dashboard');revalidatePath(`/${shop.slug}`);return{success:'Serviço salvo.'};}catch(error){return{error:errorMessage(error)};}}
export async function saveBarber(form:FormData):Promise<ActionResult>{const{db,shop}=await requireTenant();try{const data=barberSchema.parse({...values(form),active:form.get('active')==='on'});const id=form.get('id');const query=id?db.from('barbers').update(data).eq('id',uuid.parse(id)).eq('barbershop_id',shop.id):db.from('barbers').insert({...data,barbershop_id:shop.id});const{error}=await query;if(error)throw error;revalidatePath('/dashboard');return{success:'Barbeiro salvo. Configure os horários e vincule os serviços para receber reservas.'};}catch(error){return{error:errorMessage(error)};}}
export async function saveShop(form:FormData):Promise<ActionResult>{const{db,shop}=await requireTenant();try{const data=shopSchema.parse({...values(form),booking_enabled:form.get('booking_enabled')==='on',notifications_enabled:form.get('notifications_enabled')==='on'});const{error}=await db.rpc('update_shop',{p_shop:shop.id,p_data:data});if(error)throw error;revalidatePath('/dashboard');revalidatePath(`/${shop.slug}`);revalidatePath(`/${data.slug}`);return{success:'Página atualizada.'};}catch(error){return{error:errorMessage(error)};}}
export async function saveHours(form:FormData):Promise<ActionResult>{const{db,shop}=await requireTenant();try{const barber=form.get('barber_id')?uuid.parse(form.get('barber_id')):null;const windows:z.infer<typeof hourSchema>[]=[];for(let d=0;d<7;d++){if(form.get(`enabled_${d}`)!=='on')continue;for(let n=0;n<2;n++){const opens=form.get(`open_${d}_${n}`);const closes=form.get(`close_${d}_${n}`);if(opens||closes)windows.push(hourSchema.parse({weekday:d,opens_at:opens,closes_at:closes}));}}const{error}=await db.rpc('replace_hours',{p_shop:shop.id,p_barber:barber,p_hours:windows});if(error)throw error;revalidatePath('/dashboard');return{success:'Horários atualizados.'};}catch(error){return{error:errorMessage(error)};}}
const hourSchema=z.object({weekday:z.number().int().min(0).max(6),opens_at:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),closes_at:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/)}).refine(v=>v.opens_at<v.closes_at,'A abertura deve ser anterior ao encerramento.');
export async function addBlock(form:FormData):Promise<ActionResult>{const{db,shop}=await requireTenant();try{const v=z.object({barber_id:uuid.or(z.literal('')),starts_at:z.string().min(16),ends_at:z.string().min(16),reason:z.string().trim().min(2).max(200)}).parse(values(form));const{error}=await db.rpc('add_block',{p_shop:shop.id,p_barber:v.barber_id||null,p_start:v.starts_at,p_end:v.ends_at,p_reason:v.reason});if(error)throw error;revalidatePath('/dashboard');return{success:'Bloqueio adicionado.'};}catch(error){return{error:errorMessage(error)};}}
export async function removeBlock(form:FormData):Promise<ActionResult>{const{db,shop}=await requireTenant();try{const{error}=await db.from('blocked_times').delete().eq('id',uuid.parse(form.get('id'))).eq('barbershop_id',shop.id);if(error)throw error;revalidatePath('/dashboard');return{success:'Bloqueio removido.'};}catch(error){return{error:errorMessage(error)};}}
export async function manageAppointment(form:FormData):Promise<ActionResult>{const{db}=await requireTenant();try{const id=uuid.parse(form.get('id'));const status=z.enum(['PENDING','CONFIRMED','COMPLETED','CANCELLED','NO_SHOW']).parse(form.get('status'));const start=form.get('starts_at');const{error}=await db.rpc('manage_appointment',{p_id:id,p_status:status,p_start:start?z.string().datetime({offset:true}).parse(start):null,p_barber:form.get('barber_id')?uuid.parse(form.get('barber_id')):null,p_service:form.get('service_id')?uuid.parse(form.get('service_id')):null});if(error)throw error;revalidatePath('/dashboard');return{success:'Agendamento atualizado.'};}catch(error){return{error:errorMessage(error)};}}
export async function adminUpdate(form:FormData):Promise<ActionResult>{const{db}=await requireAdmin();try{const{error}=await db.rpc('admin_update_shop',{p_shop:uuid.parse(form.get('id')),p_suspended:form.get('suspended')==='on',p_plan:z.enum(['FREE','PRO']).parse(form.get('plan'))});if(error)throw error;revalidatePath('/admin');return{success:'Barbearia atualizada.'};}catch(error){return{error:errorMessage(error)};}}
