import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile,readdir } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { btree_gist } from '@electric-sql/pglite/contrib/btree_gist';
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto';

test('PostgreSQL: isolamento, autorização, janelas e integridade de reservas',async(t)=>{
 const db=new PGlite({extensions:{btree_gist,pgcrypto}});
 await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
 create schema auth; create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to anon,authenticated,service_role; grant execute on function auth.uid() to anon,authenticated,service_role;
 create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
 create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;`);
 for(const file of (await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(`supabase/migrations/${file}`,'utf8'));
 const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
 await db.query('insert into auth.users(id) values($1),($2)',[owner,other]);
 async function asUser(id:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
 const data={name:'Corte Fino',slug:'corte-fino',whatsapp:'11999999999',phone:'11999999999',service_name:'Corte',price_cents:4000,duration_minutes:30,barber_name:'João',specialties:'Corte',opens_at:'09:00',closes_at:'18:00'};
 await asUser(owner);const result=await db.query<{id:string}>('select create_barbershop($1::jsonb) id',[JSON.stringify(data)]);const shop=result.rows[0].id;
 const barber=(await db.query<{id:string}>('select id from barbers')).rows[0].id;const service=(await db.query<{id:string}>('select id from services')).rows[0].id;
 await asUser(other);const shop2=(await db.query<{id:string}>('select create_barbershop($1::jsonb) id',[JSON.stringify({...data,slug:'barber-house'})])).rows[0].id;
 const barber2=(await db.query<{id:string}>('select id from barbers')).rows[0].id;
 await t.test('tenant B não lê A nem altera referências para A',async()=>{assert.equal((await db.query('select * from services where barbershop_id=$1',[shop])).rows.length,0);await assert.rejects(db.query("insert into barber_services(barbershop_id,barber_id,service_id) values($1,$2,$3)",[shop2,barber2,service]));assert.equal((await db.query('update barbers set name=$1 where id=$2 returning id',['Intruso',barber])).rows.length,0);await assert.rejects(db.query('select manage_appointment($1,$2)',[crypto.randomUUID(),'CANCELLED']));});
 await t.test('papel global e planos não podem ser promovidos por usuário',async()=>{await assert.rejects(db.query("update profiles set role='ADMIN' where id=$1",[other]));await assert.rejects(db.query("update subscriptions set plan='PRO' where barbershop_id=$1",[shop2]));await assert.rejects(db.query('select admin_update_shop($1,false,$2)',[shop,'PRO']));});
 await db.exec("reset role; set role anon; select set_config('request.jwt.claim.sub','',false)");
 await t.test('anônimo só recebe projeção pública e não acessa clientes',async()=>{await assert.rejects(db.query('select * from customers'));const{rows}=await db.query<{data:{barbers:Record<string,unknown>[]}}>('select public_shop($1) data',['corte-fino']);assert.equal(rows[0].data.barbers[0].email,undefined);await assert.rejects(db.query('select consume_rate_limit($1,10,60)',['bypass']));});
 await db.exec('reset role');
 const date=(await db.query<{d:string}>("select to_char(current_date+case when extract(dow from current_date+1)=0 then 2 else 1 end,'YYYY-MM-DD') d")).rows[0].d;
 await asUser(owner);
 const weekday=new Date(date+'T12:00:00Z').getUTCDay();
 await db.query('select replace_hours($1,$2,$3::jsonb)',[shop,barber,JSON.stringify([{weekday,opens_at:'09:00',closes_at:'12:00'},{weekday,opens_at:'13:00',closes_at:'18:00'}])]);
 await db.query('select add_block($1,$2,$3,$4,$5)',[shop,barber,date+'T15:00',date+'T16:00','Folga']);
 await db.exec("reset role; select set_config('request.jwt.claim.sub','',false)");
 const slots=await db.query<{starts_at:Date}>('select * from available_slots($1,$2,$3,$4)',['corte-fino',service,barber,date]);
 const hours=slots.rows.map(r=>new Date(r.starts_at).toISOString().slice(11,16));
 await t.test('intervalo, bloqueio, duração e timezone respeitados',()=>{assert.ok(hours.includes('12:00'));assert.ok(hours.includes('14:30'));assert.ok(!hours.includes('14:35'));assert.ok(!hours.includes('15:00'));assert.ok(hours.includes('16:00'));assert.ok(!hours.includes('18:00'));assert.ok(hours.includes('19:00'));assert.ok(!hours.includes('20:35'));});
 const start=new Date(slots.rows[0].starts_at).toISOString();
 const book=()=>db.query('select book_appointment($1,$2,$3,$4,$5,$6,$7,$8)',['corte-fino',service,barber,start,'Pedro','11988887777','11988887777','pedro@example.com']);
 await t.test('reserva cria cliente e snapshot; segunda tentativa é rejeitada',async()=>{await book();await assert.rejects(book(),/Horário indisponível/);assert.equal((await db.query('select * from appointments where barbershop_id=$1',[shop])).rows.length,1);assert.equal((await db.query('select * from customers where barbershop_id=$1',[shop])).rows.length,1);});
 await t.test('constraint impede sobreposição até por inserção privilegiada',async()=>{await assert.rejects(db.query("insert into appointments(barbershop_id,barber_id,service_id,customer_id,starts_at,ends_at,price_cents) select barbershop_id,barber_id,service_id,customer_id,starts_at+interval '5 minutes',ends_at+interval '5 minutes',price_cents from appointments where barbershop_id=$1",[shop]),/exclusion constraint/);});
 await t.test('preço passado pelo cliente não faz parte da RPC',async()=>{const{rows}=await db.query<{price_cents:number}>('select price_cents from appointments where barbershop_id=$1',[shop]);assert.equal(rows[0].price_cents,4000);});
 await asUser(owner);const appointment=(await db.query<{id:string}>('select id from appointments')).rows[0].id;
 await t.test('bloqueios com reservas ativas são rejeitados',async()=>{await assert.rejects(db.query('select add_block($1,$2,$3,$4,$5)',[shop,barber,date+'T09:00',date+'T10:00','Folga']),/agendamentos/);});
 await t.test('cancelamento libera horário; completar futuro é recusado',async()=>{await assert.rejects(db.query('select manage_appointment($1,$2)',[appointment,'COMPLETED']),/não começou/);await db.query('select manage_appointment($1,$2)',[appointment,'CANCELLED']);assert.ok((await db.query('select * from available_slots($1,$2,$3,$4) where starts_at=$5',['corte-fino',service,barber,date,start])).rows.length);});
 await db.exec('reset role');await db.query('update barbershops set booking_enabled=false where id=$1',[shop]);
 await t.test('pausa impede slots e novas reservas',async()=>{assert.equal((await db.query('select * from available_slots($1,$2,$3,$4)',['corte-fino',service,barber,date])).rows.length,0);await assert.rejects(book(),/indisponíveis/);});
 await db.close();
});
