import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalLayout } from '@/components/legal-layout';
export const metadata:Metadata={title:'Termos de Uso'};
export default function Terms(){return <LegalLayout title="Termos de Uso">
 <section><h2 className="section-title">1. Sobre o Zekro</h2><p>O Zekro oferece ferramentas para organizar agenda, profissionais, serviços e clientes de barbearias. O serviço de barbearia é prestado pelo estabelecimento escolhido, que responde por seus preços, atendimento e regras de cancelamento. O Zekro não recebe o pagamento desses atendimentos nesta versão.</p></section>
 <section><h2 className="section-title">2. Conta e acesso</h2><p>O responsável deve fornecer informações corretas, proteger suas credenciais e atribuir permissões apenas a pessoas autorizadas. É possível entrar por email e senha ou pelo Google quando o provedor estiver habilitado. Não compartilhe senhas. A conta não deve ser usada para fraudes, envio de dados obtidos ilegalmente ou tentativa de acesso a outras barbearias.</p></section>
 <section><h2 className="section-title">3. Teste e contratação</h2><p>O teste dura 7 dias a partir da criação da barbearia. Não exige pagamento e não há renovação automática. Após o teste, Zekro Pro custa R$ 49,90 por 30 dias de acesso. O pagamento é feito por Pix direto para a conta indicada nas instruções do painel.</p><p>Confira o titular da conta e o valor no banco antes de transferir. A solicitação de conferência não prova recebimento: o administrador verifica o crédito no extrato antes de liberar o acesso. A confirmação acrescenta 30 dias ao prazo vigente, preservando o restante do teste ou do período já contratado.</p><p>Não há cobrança automática, débito recorrente ou intermediário de pagamento integrado. Eventuais tarifas do Pix dependem do banco. Não faça um segundo pagamento enquanto o primeiro estiver em conferência. Para renovar, solicite novas instruções no painel.</p></section>
 <section><h2 className="section-title">4. Expiração e cancelamento</h2><p>Sem acesso vigente, novas reservas, remarcações e reativações ficam pausadas. O histórico e a administração de reservas existentes continuam disponíveis enquanto a conta estiver ativa e autorizada. Para interromper novas contratações, basta não renovar. Se desejar encerrar a conta ou solicitar reembolso, use o <Link className="underline" href="/contato">canal de suporte</Link>. Direitos legais aplicáveis, inclusive o direito de arrependimento quando cabível, permanecem assegurados.</p></section>
 <section><h2 className="section-title">5. Dados e responsabilidades</h2><p>A barbearia deve cadastrar somente dados necessários, informar os clientes sobre o uso de seus dados e respeitar a legislação aplicável. Reservas públicas podem ser feitas sem uma conta. As práticas de tratamento estão descritas na <Link className="underline" href="/privacidade">Política de Privacidade</Link>.</p></section>
 <section><h2 className="section-title">6. Disponibilidade e segurança</h2><p>Manutenções, falhas de conexão e indisponibilidade de fornecedores podem afetar o serviço. Não há promessa de disponibilidade ininterrupta. Use informações de contato atualizadas e mantenha seus próprios registros essenciais. Atividades abusivas podem ser limitadas ou suspensas, sem afastar os direitos previstos em lei.</p></section>
 <section><h2 className="section-title">7. Alterações e contato</h2><p>Alterações materiais nos termos ou no preço devem ser informadas antes de uma nova contratação. Estas condições não autorizam cobranças não solicitadas nem afastam direitos do consumidor. A identificação do responsável e o atendimento estão na <Link className="underline" href="/contato">página de contato</Link>.</p></section>
 </LegalLayout>;}
