'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowUpRight, Loader2 } from 'lucide-react';
import { Field } from '@/components/ui';
export function AuthForm({mode,ready}:{mode:'login'|'register'|'recover'|'reset';ready:boolean}){
 const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const router=useRouter();
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');const values=Object.fromEntries(new FormData(e.currentTarget));try{
 if(mode==='recover'){const res=await fetch('/api/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await res.json();if(!res.ok)throw new Error(data.error);setMessage('Se este email estiver cadastrado, você receberá um link para redefinir a senha.');}
 else if(mode==='reset'){const res=await fetch('/api/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await res.json();if(!res.ok)throw new Error(data.error);router.push('/login?reset=1');router.refresh();return;}
 else{const res=await fetch(`/api/${mode==='register'?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await res.json();if(!res.ok)throw new Error(data.error);if(mode==='register'&&!data.session)setMessage('Confira seu email e confirme sua conta para configurar a barbearia.');else{router.push(mode==='register'?'/onboarding':'/dashboard');router.refresh();}}
 }catch(error){setError(error instanceof Error?error.message:'Erro de conexão. Tente novamente.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="form-stack mt-8">{!ready&&<p className="notice">Ambiente ainda não conectado. Configure o Supabase conforme o README para habilitar contas reais.</p>}{mode==='register'&&<Field label="Nome do responsável"><input name="name" autoComplete="name" required minLength={2} maxLength={120} placeholder="Como podemos chamar você?"/></Field>}{mode!=='reset'&&<Field label="Email"><input name="email" type="email" autoComplete="email" required placeholder="voce@exemplo.com"/></Field>}{mode!=='recover'&&<Field label="Senha" hint={mode==='register'||mode==='reset'?'Use pelo menos 10 caracteres.':undefined}><input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:10} maxLength={128} required placeholder="Sua senha"/></Field>}{mode==='login'&&<Link href="/recuperar-senha" className="text-sm underline self-end">Esqueci minha senha</Link>}{error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice success">{message}</p>}<button disabled={busy||!ready} className="btn btn-dark w-full">{busy?<Loader2 size={17} className="animate-spin"/>:<ArrowUpRight size={17}/>}{{login:'Entrar na minha conta',register:'Criar minha conta',recover:'Enviar link de recuperação',reset:'Salvar nova senha'}[mode]}</button></form>;
}
