'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowUpRight, Loader2 } from 'lucide-react';
import { Field } from '@/components/ui';
export function AuthForm({mode,ready}:{mode:'login'|'register'|'recover'|'reset';ready:boolean}){
 const[message,setMessage]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const router=useRouter();
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setMessage('');const values=Object.fromEntries(new FormData(e.currentTarget));try{
 if(mode==='recover'){const res=await fetch('/api/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await res.json();if(!res.ok)throw new Error(data.error);setMessage('Se este email estiver cadastrado, você receberá um link para redefinir a senha.');}
 else if(mode==='reset'){const res=await fetch('/api/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await res.json();if(!res.ok)throw new Error(data.error);router.push('/login?reset=1');router.refresh();return;}
 else{const res=await fetch(`/api/${mode==='register'?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await res.json();if(!res.ok)throw new Error(data.error);if(mode==='register'&&!data.session)setMessage('Confira seu email e confirme sua conta para configurar a barbearia.');else{router.push(mode==='register'?'/onboarding':'/dashboard');router.refresh();}}
 }catch(error){setError(error instanceof Error?error.message:'Erro de conexão. Tente novamente.');}finally{setBusy(false);}}
 return <>{(mode==='login'||mode==='register')&&<div className="mt-7"><Link href="/auth/google" className="btn btn-outline w-full"><svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.39-.18-2.05H12v3.88h5.38a4.6 4.6 0 0 1-2 3.02v2.51h3.24c1.9-1.75 2.98-4.32 2.98-7.36Z"/><path fill="#34A853" d="M12 22c2.7 0 4.96-.9 6.62-2.41l-3.24-2.51c-.9.6-2.05.96-3.38.96-2.61 0-4.82-1.76-5.61-4.12H3.05v2.59A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.39 13.92a6 6 0 0 1 0-3.84V7.49H3.05a10 10 0 0 0 0 9.02l3.34-2.59Z"/><path fill="#EA4335" d="M12 5.96c1.47 0 2.79.5 3.83 1.49l2.87-2.87A9.62 9.62 0 0 0 12 2a10 10 0 0 0-8.95 5.49l3.34 2.59C7.18 7.72 9.39 5.96 12 5.96Z"/></svg>Entrar com Google</Link><p className="text-xs muted text-center mt-5">ou continue com seu email</p></div>}<form onSubmit={submit} className="form-stack mt-8">{!ready&&<p className="notice">Ambiente ainda não conectado. Configure o Supabase conforme o README para habilitar contas reais.</p>}{mode==='register'&&<Field label="Nome do responsável"><input name="name" autoComplete="name" required minLength={2} maxLength={120} placeholder="Como podemos chamar você?"/></Field>}{mode!=='reset'&&<Field label="Email"><input name="email" type="email" autoComplete="email" required placeholder="voce@exemplo.com"/></Field>}{mode!=='recover'&&<Field label="Senha" hint={mode==='register'||mode==='reset'?'Use pelo menos 10 caracteres.':undefined}><input name="password" type="password" autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?1:10} maxLength={128} required placeholder="Sua senha"/></Field>}{mode==='register'&&<label className="flex gap-2 items-start text-xs leading-relaxed"><input type="checkbox" name="acceptedTerms" required/><span>Li e aceito os <Link href="/termos" target="_blank" className="underline">Termos de Uso</Link> e li a <Link href="/privacidade" target="_blank" className="underline">Política de Privacidade</Link>.</span></label>}{mode==='login'&&<Link href="/recuperar-senha" className="text-sm underline self-end">Esqueci minha senha</Link>}{error&&<p role="alert" className="notice error">{error}</p>}{message&&<p role="status" className="notice success">{message}</p>}<button disabled={busy||!ready} className="btn btn-dark w-full">{busy?<Loader2 size={17} className="animate-spin"/>:<ArrowUpRight size={17}/>}{{login:'Entrar na minha conta',register:'Criar minha conta',recover:'Enviar link de recuperação',reset:'Salvar nova senha'}[mode]}</button></form><p className="text-xs muted mt-5"><Link href="/termos" className="underline">Termos</Link> · <Link href="/privacidade" className="underline">Privacidade</Link> · <Link href="/contato" className="underline">Suporte</Link></p></>;
}
