'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Field } from '@/components/ui';
import { onboard } from '@/services/actions';
import { weekdays } from '@/utils/format';

const steps=['Criar conta','Sua barbearia','Primeiro profissional','Serviços e preços','Horários','Personalizar página','Publicar link'];
const initial:Record<string,string>={name:'',phone:'',whatsapp:'',instagram:'',address:'',city:'',state:'',description:'',slug:'',barber_name:'',specialties:'',service_name:'',price:'40',duration_minutes:'30',opens_at:'09:00',closes_at:'18:00',timezone:'America/Sao_Paulo',primary_color:'#153d2e'};
export function OnboardingForm({userId}:{userId:string}) {
 const [step,setStep]=useState(1),[draft,setDraft]=useState(initial),[days,setDays]=useState([1,2,3,4,5,6]);
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const form=useRef<HTMLFormElement>(null),heading=useRef<HTMLHeadingElement>(null),router=useRouter();
 const key=`zekro-onboarding-v2:${userId}`;
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');if(saved&&typeof saved==='object'){const restored={...initial};for(const name of Object.keys(initial))if(typeof saved.draft?.[name]==='string')restored[name]=saved.draft[name];setDraft(restored);if(Array.isArray(saved.days)&&saved.days.length&&saved.days.every((d:unknown)=>Number.isInteger(d)&&Number(d)>=0&&Number(d)<=6))setDays(saved.days);}}catch{/* A draft is optional. */}setReady(true);},[key]);
 useEffect(()=>{if(ready)try{sessionStorage.setItem(key,JSON.stringify({draft,days}));}catch{/* Private browsing can disable storage. */}},[draft,days,key,ready]);
 useEffect(()=>{heading.current?.focus();},[step]);
 function input(name:string){return {name,value:draft[name],onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setDraft({...draft,[name]:e.target.value})};}
 function valid(index:number){const fields=form.current?.querySelector(`[data-step="${index}"]`)?.querySelectorAll<HTMLInputElement>('input,textarea,select');return !fields||Array.from(fields).every(field=>field.reportValidity());}
 function next(){setError('');if(!valid(step))return;if(step===4&&(!days.length||draft.opens_at>=draft.closes_at)){setError('Escolha pelo menos um dia e um encerramento após a abertura.');return;}setStep(step+1);}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;if(step<6){next();return;}for(let index=1;index<=6;index++){if(!valid(index)){setStep(index);return;}}setBusy(true);setError('');try{const result=await onboard(new FormData(event.currentTarget));if(result.error)setError(result.error);if(result.redirect){try{sessionStorage.removeItem(key);}catch{}router.push(result.redirect);router.refresh();}}catch{setError('Não foi possível salvar. Seu rascunho foi mantido; tente novamente.');}finally{setBusy(false);}}
 return <><ol className="onboarding-steps">{steps.map((label,index)=><li key={label} aria-current={index===step?'step':undefined}>{index===0?'✓':index+1} · {label}</li>)}</ol><progress max={7} value={step+1} aria-label={`Etapa ${step+1} de 7`}/><form ref={form} onSubmit={submit} noValidate className="card p-6 md:p-9 form-stack mt-5"><h2 ref={heading} tabIndex={-1} className="section-title">{steps[step]}</h2><p className="muted text-sm">Sua conta já está pronta. Você pode voltar e revisar os dados antes de publicar.</p><fieldset disabled={busy||!ready} className="contents">
 <section data-step="1" hidden={step!==1} className="form-stack"><Field label="Nome da barbearia"><input {...input('name')} minLength={2} maxLength={120} required/></Field><div className="form-grid"><Field label="WhatsApp com DDD"><input {...input('whatsapp')} type="tel" minLength={10} maxLength={30} required/></Field><Field label="Telefone (opcional)"><input {...input('phone')} type="tel" maxLength={30}/></Field></div></section>
 <section data-step="2" hidden={step!==2} className="form-stack"><Field label="Nome do profissional"><input {...input('barber_name')} minLength={2} maxLength={120} required/></Field><Field label="Especialidades"><input {...input('specialties')} maxLength={500}/></Field><p className="notice">Pode ser você. Depois, adicione sua equipe e configure horários individuais.</p></section>
 <section data-step="3" hidden={step!==3} className="form-stack"><Field label="Primeiro serviço"><input {...input('service_name')} minLength={2} maxLength={120} placeholder="Corte masculino" required/></Field><div className="form-grid"><Field label="Preço (R$)"><input {...input('price')} type="number" min="0" max="100000" step="0.01" required/></Field><Field label="Duração (minutos)"><input {...input('duration_minutes')} type="number" min="5" max="480" required/></Field></div><p className="notice">Este serviço será vinculado ao primeiro profissional. Outros serviços podem ser cadastrados no painel.</p></section>
 <section data-step="4" hidden={step!==4} className="form-stack"><div className="flex flex-wrap gap-4">{weekdays.map((label,index)=><label className="flex gap-2 items-center" key={label}><input name="weekdays" value={index} type="checkbox" checked={days.includes(index)} onChange={e=>setDays(e.target.checked?[...days,index]:days.filter(d=>d!==index))}/>{label}</label>)}</div><div className="form-grid"><Field label="Abertura"><input {...input('opens_at')} type="time" required/></Field><Field label="Encerramento"><input {...input('closes_at')} type="time" required/></Field></div><Field label="Fuso horário"><select {...input('timezone')}>{['America/Sao_Paulo','America/Manaus','America/Rio_Branco','America/Noronha','America/Cuiaba'].map(t=><option key={t}>{t}</option>)}</select></Field><p className="notice">O profissional começa com estes horários. Intervalos e folgas específicas ficam em Configurações.</p></section>
 <section data-step="5" hidden={step!==5} className="form-stack"><Field label="Endereço do link" hint={`Sua página: /${draft.slug||'sua-barbearia'}`}><input {...input('slug')} pattern="[a-z0-9][a-z0-9-]{2,59}" required minLength={3} maxLength={60}/></Field><Field label="Descrição"><textarea {...input('description')} maxLength={2000}/></Field><div className="form-grid"><Field label="Cor da identidade"><input {...input('primary_color')} type="color"/></Field><Field label="Instagram"><input {...input('instagram')} maxLength={150}/></Field><Field label="Endereço"><input {...input('address')} maxLength={300}/></Field><Field label="Cidade"><input {...input('city')} maxLength={120}/></Field><Field label="Estado (UF)"><input {...input('state')} maxLength={2}/></Field></div><p className="notice">Após criar sua barbearia, você pode enviar logo e capa e visualizar a página no painel.</p></section>
 <section data-step="6" hidden={step!==6} className="form-stack"><div className="card p-6" style={{borderTop:`5px solid ${draft.primary_color}`}}><h3>{draft.name||'Sua barbearia'}</h3><p className="muted mt-3">{draft.description}</p><p className="mt-3">{draft.service_name} · R$ {draft.price} · {draft.duration_minutes} min</p><p>{draft.barber_name} · {draft.opens_at}–{draft.closes_at}</p><p>{days.map(d=>weekdays[d]).join(', ')}</p><p className="break-all mt-3">/{draft.slug}</p></div><label className="flex gap-2 items-start text-sm"><input type="checkbox" name="accepted_terms" required/><span>Li e aceito os <Link href="/termos" target="_blank" className="underline">Termos de Uso</Link> e li a <Link href="/privacidade" target="_blank" className="underline">Política de Privacidade</Link>. Teste de 7 dias, depois R$ 49,90/mês via Pix com conferência administrativa e sem renovação automática.</span></label></section>
 </fieldset>{error&&<p role="alert" className="notice error">{error}</p>}<div className="flex justify-between flex-wrap gap-3"><button type="button" disabled={busy||step===1} className="btn btn-outline" onClick={()=>setStep(step-1)}>Voltar</button><button disabled={busy||!ready} className="btn btn-dark">{busy?'Criando sua barbearia…':step===6?'Publicar link de agendamento':'Continuar →'}</button></div></form></>;
}
