import Link from 'next/link';
import { ArrowUpRight, CalendarDays } from 'lucide-react';
import type { Status } from '@/types/domain';
import { statusLabels } from '@/utils/format';
export function LogoMark({size=38}:{size?:number}){return <svg className="logo-mark" viewBox="0 0 64 64" width={size} height={size} aria-hidden="true"><defs><linearGradient id="zk-bg" x1="8" y1="4" x2="56" y2="62" gradientUnits="userSpaceOnUse"><stop stopColor="#22604a"/><stop offset="1" stopColor="#0b2219"/></linearGradient><linearGradient id="zk-z" x1="16" y1="16" x2="48" y2="48" gradientUnits="userSpaceOnUse"><stop stopColor="#e6ffb8"/><stop offset="1" stopColor="#9fd651"/></linearGradient></defs><rect width="64" height="64" rx="17" fill="url(#zk-bg)"/><rect x="1.5" y="1.5" width="61" height="61" rx="15.5" fill="none" stroke="#fff" strokeOpacity=".1"/><path fill="url(#zk-z)" d="M17 16.5h25.5c2.6 0 4.3 2.8 3 5.1L26.4 42H44a3.5 3.5 0 0 1 0 7H19.4c-2.6 0-4.3-2.8-3-5.1L35.6 23.5H17a3.5 3.5 0 0 1 0-7Z"/><path fill="#fff" fillOpacity=".55" d="M45.2 22.1 26.4 42h-3.9L41.4 22Z"/><path fill="#f2ffd9" d="M50.5 8.5c.5 2.6 1.4 3.5 4 4-2.6.5-3.5 1.4-4 4-.5-2.6-1.4-3.5-4-4 2.6-.5 3.5-1.4 4-4Z"/></svg>;}
export function Logo({light=false}:{light?:boolean}){return <Link href="/" className={`logo ${light?'text-white':''}`}><LogoMark/><span className="logo-word">zekro</span></Link>;}
export function PageHeader({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:React.ReactNode}){return <div className="page-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="muted mt-2">{description}</p>}</div>{children}</div>;}
export function EmptyState({title='Tudo pronto para começar',description,href,label='Começar'}:{title?:string;description:string;href?:string;label?:string}){return <div className="empty-state"><span className="empty-icon"><CalendarDays size={26}/></span><h3>{title}</h3><p>{description}</p>{href&&<Link href={href} className="btn btn-dark mt-5">{label}<ArrowUpRight size={16}/></Link>}</div>;}
export function Badge({status}:{status:Status}){return <span className={`badge status-${status.toLowerCase()}`}>{statusLabels[status]}</span>;}
export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Stat({label,value,detail,icon}:{label:string;value:React.ReactNode;detail?:string;icon?:React.ReactNode}){return <div className="stat-card"><div className="flex justify-between items-center"><p>{label}</p><span className="muted">{icon}</span></div><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
