'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { LayoutDashboard,CalendarDays,ClipboardList,Users,Scissors,Sparkles,Globe,BarChart3,Settings,ArrowUpRight,LogOut,Menu,X,ChevronDown,ShieldCheck } from 'lucide-react';
import { Logo } from '@/components/ui';
import { logout } from '@/services/actions';
const links=[['/dashboard','Dashboard',LayoutDashboard],['/dashboard/agenda','Agenda',CalendarDays],['/dashboard/agendamentos','Agendamentos',ClipboardList],['/dashboard/clientes','Clientes',Users],['/dashboard/barbeiros','Barbeiros',Scissors],['/dashboard/servicos','Serviços',Sparkles],['/dashboard/pagina','Página da Barbearia',Globe],['/dashboard/relatorios','Relatórios',BarChart3],['/dashboard/configuracoes','Configurações',Settings]] as const;
export function DashboardShell({children,shop,name,plan,admin,owner=true}:{owner?:boolean;children:React.ReactNode;shop:{name:string;slug:string};name:string;plan:string;admin:boolean}){const pathname=usePathname();const[open,setOpen]=useState(false);return <>{open&&<button className="sidebar-overlay" aria-label="Fechar menu" onClick={()=>setOpen(false)}/>}<aside id="workspace-navigation" onKeyDown={event=>{if(event.key==='Escape')setOpen(false);}} className={`sidebar ${open?'open':''}`}><div className="flex justify-between items-center"><Logo/><button className="mobile-menu" aria-label="Fechar menu" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="workspace-switch"><span className="avatar !rounded-lg !w-8 !h-8"><Scissors size={16}/></span><div className="min-w-0 flex-1"><strong className="truncate">{shop.name}</strong><small>Meu espaço de trabalho</small></div><ChevronDown size={13} className="muted"/></div><p className="side-label">PRINCIPAL</p><nav className="side-links" aria-label="Navegação do painel">{links.filter(([href])=>owner||href!=='/dashboard/pagina').map(([href,label,Icon])=><Link onClick={()=>setOpen(false)} href={href} key={href} className={(href==='/dashboard'?pathname===href:pathname.startsWith(href))?'active':''}><Icon/>{label}</Link>)}{admin&&<Link href="/admin"><ShieldCheck/>Administração SaaS</Link>}</nav><div className="sidebar-bottom"><div className="upgrade-card"><p className="eyebrow !mt-0 !mb-2">SEU PLANO · {plan==='PRO'?'ZEKRO PRO':'ACESSO ENCERRADO'}</p><h3>Pronto para o próximo nível?</h3><p>Conheça o espaço que seu negócio tem para crescer.</p><Link href="/dashboard/configuracoes#plano" className="text-[10px] font-semibold mt-3 flex items-center gap-2">Conhecer meu plano<ArrowUpRight size={12}/></Link></div><form action={logout} className="mt-5"><button className="flex items-center gap-2 text-xs muted px-3"><LogOut size={15}/>Sair da conta</button></form></div></aside><div className="app-main"><header className="topbar"><div className="flex items-center gap-3"><button className="mobile-menu" onClick={()=>setOpen(true)} aria-expanded={open} aria-controls="workspace-navigation" aria-label="Abrir menu"><Menu size={20}/></button><p className="topbar-title">Meu espaço <span className="mx-3 text-[#c0c8ba]">/</span> <span className="text-[var(--ink)]">{links.find(([href])=>href===pathname)?.[1]||'Minha barbearia'}</span></p></div><div className="flex items-center gap-5"><Link href={`/${shop.slug}`} target="_blank" className="text-[11px] muted flex gap-2 items-center">Ver página pública<ArrowUpRight size={14}/></Link><div className="h-6 w-px bg-[var(--line)]"/><span className="avatar !w-8 !h-8">{name.slice(0,2).toUpperCase()}</span></div></header><main className="app-content">{children}</main></div></>;}
