import Link from 'next/link';
import { Field,Stat } from '@/components/ui';
import type { AnalyticsSummary } from '@/types/product';
import { money,day } from '@/utils/format';
export function PeriodFilter({from,to,error}:{from:string;to:string;error?:string}){return <><form className="filters items-end"><Field label="De"><input type="date" name="from" defaultValue={from} required/></Field><Field label="Até"><input type="date" name="to" defaultValue={to} required/></Field><button className="btn btn-dark">Aplicar período</button></form>{error&&<p role="alert" className="notice error mb-5">{error}</p>}</>;}
export function Summary({value,dashboard=false}:{value:AnalyticsSummary;dashboard?:boolean}){return <div className="section-stack"><div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{dashboard&&<><Stat label="Agendamentos de hoje" value={value.today}/><Stat label="Próximos 7 dias" value={value.week}/><Stat label="Clientes cadastrados" value={value.customers}/><Stat label="Clientes novos no período" value={value.newCustomers}/></>}<Stat label="Faturamento previsto" value={money(value.expected)} detail="Reservas ativas e serviços concluídos"/><Stat label="Recebimentos registrados" value={money(value.received)} detail="Data de recebimento; exclui anulados"/><Stat label="Cancelamentos no período" value={value.cancelled}/><Stat label="Taxa de ocupação" value={value.occupancy===null?'—':`${value.occupancy}%`} detail="Sobre os horários atualmente configurados"/></div><p className="notice">Concluir um atendimento não registra seu pagamento. Registre o recebimento em <Link className="underline" href="/dashboard/financeiro">Financeiro</Link> depois de conferir o valor. A ocupação considera profissionais ativos, intervalos e bloqueios; mudanças de horários recalculam períodos anteriores.</p><div className="grid xl:grid-cols-2 gap-6"><BarChart title="Atendimentos concluídos por dia" points={value.daily.map(d=>({label:d.date,value:d.completed}))}/><BarChart title="Recebimentos por dia" currency points={value.daily.map(d=>({label:d.date,value:d.received}))}/></div><div className="grid md:grid-cols-2 gap-6">{[{title:'Serviços mais procurados',items:value.services},{title:'Desempenho por profissional',items:value.barbers}].map(group=><section className="card p-6" key={group.title}><h2 className="section-title mb-5">{group.title}</h2>{group.items.length?group.items.map(item=><div key={item.id} className="mb-5"><div className="flex justify-between gap-4 text-sm"><span>{item.name}</span><span>{item.count} concluídos · {money(item.received)} recebidos</span></div><div className="progress-track mt-2" aria-hidden="true"><div style={{width:`${item.count/Math.max(1,...group.items.map(i=>i.count))*100}%`}}/></div></div>):<p className="muted">Nenhum atendimento concluído ou recebimento neste período.</p>}</section>)}</div></div>;}
function BarChart({title,points,currency=false}:{title:string;points:{label:string;value:number}[];currency?:boolean}){
 const max=Math.max(1,...points.map(p=>p.value));
 return <section className="card p-6 min-w-0"><h2 className="section-title">{title}</h2><div className="chart-bars" aria-hidden="true">{points.map(p=><div key={p.label} title={`${day(p.label+'T12:00Z','UTC')}: ${currency?money(p.value):p.value}`}><span>{currency?money(p.value):p.value}</span><i style={{height:`${Math.max(2,p.value/max*140)}px`}}/><span>{p.label.slice(8)}/{p.label.slice(5,7)}</span></div>)}</div><details className="mt-4"><summary className="text-sm underline">Ver dados em tabela</summary><div className="table-scroll"><table><caption className="sr-only">{title}</caption><thead><tr><th>Data</th><th>{currency?'Recebido':'Atendimentos'}</th></tr></thead><tbody>{points.map(p=><tr key={p.label}><td>{day(p.label+'T12:00Z','UTC')}</td><td>{currency?money(p.value):p.value}</td></tr>)}</tbody></table></div></details></section>;
}
