import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalLayout } from '@/components/legal-layout';
export const metadata:Metadata={title:'Política de Privacidade'};
export default function Privacy(){return <LegalLayout title="Política de Privacidade">
 <section><h2 className="section-title">Quais dados são tratados</h2><p>Contas utilizam nome, email, identificadores de autenticação e permissões. Ao entrar pelo Google, o provedor compartilha dados básicos da conta necessários ao login, conforme a autorização apresentada. O Zekro não solicita acesso ao Gmail, Google Drive ou contatos.</p><p>Agendamentos utilizam nome, telefone, WhatsApp e, quando informado, email, além de serviço, profissional, horário e histórico de atendimento. A barbearia pode manter dados operacionais de funcionários e clientes. Solicitações de Pix registram referência, valor, situação e, após conferência, identificador bancário EndToEnd, administrador e data da confirmação. Não são solicitadas senhas bancárias nem dados completos de cartão.</p></section>
 <section><h2 className="section-title">Finalidades e bases legais</h2><p>Os dados são usados para autenticação, gestão de acesso, reservas, execução do contrato, conferência de pagamentos e suporte. Controles de segurança e prevenção de abuso podem tratar identificadores de rede, inclusive em formato de hash. Conforme a operação, aplicam-se execução de contrato, cumprimento de obrigações legais ou legítimo interesse, observados os direitos dos titulares. Consentimento, quando necessário, deve ser específico e revogável.</p></section>
 <section><h2 className="section-title">Responsáveis e fornecedores</h2><p>A barbearia define as finalidades dos dados de seus clientes e responde como controladora dessas operações. A plataforma fornece o tratamento técnico necessário à prestação do serviço e responde pelas operações que define, como suas próprias contas, segurança e faturamento. Supabase e Vercel fornecem infraestrutura; Google participa apenas quando seu login é utilizado. Seu banco processa o Pix direto.</p><p>A infraestrutura pode tratar dados fora do Brasil, conforme a configuração e as condições dos fornecedores. Isso exige avaliação dos mecanismos de transferência internacional aplicáveis pelo responsável pela plataforma.</p></section>
 <section><h2 className="section-title">Proteção e minimização</h2><p>O acesso aos dados depende de autenticação, papel e barbearia. Respostas públicas de reservas não devem exibir os dados pessoais de outros clientes. Uma reserva usando um telefone existente não autoriza sobrescrever o cadastro. Não envie comprovantes com dados desnecessários, documentos pessoais ou credenciais pelo painel de Pix.</p></section>
 <section><h2 className="section-title">Cookies e conservação</h2><p>Cookies necessários mantêm a sessão e o fluxo de autenticação. Esta versão não integra rastreadores publicitários. Dados são conservados enquanto necessários à finalidade, ao suporte e às obrigações legais. Prazos específicos de retenção, exclusão e backup devem ser definidos pelo responsável de acordo com a operação. Excluir uma conta exige avaliar registros que precisam ser preservados legalmente.</p></section>
 <section><h2 className="section-title">Seus direitos</h2><p>Você pode solicitar informações, acesso, correção e, quando aplicável, exclusão, portabilidade, oposição ou revogação de consentimento. Dados de atendimentos devem ser solicitados à barbearia responsável; dados da sua conta na plataforma, ao <Link href="/contato" className="underline">suporte do Zekro</Link>. Para proteger sua privacidade, a identidade e a autorização do solicitante podem ser verificadas.</p></section>
 <section><h2 className="section-title">Atualizações e incidentes</h2><p>Esta política pode ser atualizada para refletir mudanças no serviço ou na legislação. Incidentes devem ser analisados e comunicados conforme a legislação aplicável. Não há garantia de ausência de riscos; medidas técnicas e organizacionais devem ser revisadas continuamente.</p></section>
 </LegalLayout>;}
